variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - package

linux_build:
  image: registry.zhst.com/dev/golang-version-1.17.6:latest
  tags:
    - linux 
  stage: build
  script: 
    - export GOPATH="/gocache"
    - make 
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_JOB_NAME}_${CI_PIPELINE_ID}"
    paths:
      - ./bin/*

linux_image:
  image: registry.zhst.com/dev/golang:latest
  tags:
    - linux_shell
  stage: package 
  script: 
    - make ci_image 
  dependencies:
    - linux_build
  only:
    refs:
      - master  