variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - package

amd64_build:
  image: registry.edge.com/dev/go-1.17.6:latest
  tags:
    - linux 
  stage: build
  script: 
    - export GOPATH="/gocache"
    - export GOARCH=amd64
    - make 
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_JOB_NAME}_${CI_PIPELINE_ID}"
    paths:
      - ./bin/amd64/*

arm64_build:
  image: registry.edge.com/dev/go-1.17.6:latest
  tags:
    - linux 
  stage: build
  script: 
    - export GOPATH="/gocache"
    - export GOARCH=arm64
    - make 
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_JOB_NAME}_${CI_PIPELINE_ID}"
    paths:
      - ./bin/arm64/*


linux_image:
  image: registry.edge.com/dev/golang:latest
  tags:
    - linux_shell
  stage: package 
  script: 
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - make ci_image 
  dependencies:
    - amd64_build
    - arm64_build
  # only:
  #   refs:
  #     - master  