apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-registry
  namespace: edge-cluster
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "deployments"
      - "ingress"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "delete"
      - "patch"