apiVersion: v1
kind: Service
metadata:
  name: edge-registry
  #namespace: {{.Namespace}}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s-app: edge-registry
  type: ClusterIP