name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

#   lint:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@master

#     - name: Set up Go
#       uses: actions/setup-go@v3
#       with:
#         go-version: 1.16
    
#     - name: Lint Go Code
#       run: | 
#         export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
#         go get -u golang.org/x/lint/golint 
#         make lint
        
  build:
    name: Build
    runs-on: ubuntu-latest
    #needs: [lint]
    steps:
    - name: Checkout Code
      uses: actions/checkout@master

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16
    
    - name: Build
      run: |
        chmod +x api/make_pb.sh
        chmod +x build.sh && ./build.sh
        ls -l bin/
